#define EEPROM_BOARD_X_ACCEL_OFFSET_ADDR	0
#define EEPROM_BOARD_Y_ACCEL_OFFSET_ADDR	2
#define EEPROM_BOARD_Z_ACCEL_OFFSET_ADDR	4
#define EEPROM_BOARD_X_GYRO_OFFSET_ADDR		6
#define EEPROM_BOARD_Y_GYRO_OFFSET_ADDR		8
#define EEPROM_BOARD_Z_GYRO_OFFSET_ADDR		10
#define EEPROM_BOARD_X_GYRO_OFFSET_MIN_ADDR	12
#define EEPROM_BOARD_X_GYRO_OFFSET_MAX_ADDR	14
#define EEPROM_BOARD_Y_GYRO_OFFSET_MIN_ADDR	16
#define EEPROM_BOARD_Y_GYRO_OFFSET_MAX_ADDR	18
#define EEPROM_BOARD_Z_GYRO_OFFSET_MIN_ADDR	20
#define EEPROM_BOARD_Z_GYRO_OFFSET_MAX_ADDR	22

#define EEPROM_STEER_X_ACCEL_OFFSET_ADDR	30
#define EEPROM_STEER_Y_ACCEL_OFFSET_ADDR	32
#define EEPROM_STEER_Z_ACCEL_OFFSET_ADDR	34
#define EEPROM_STEER_X_GYRO_OFFSET_ADDR		36
#define EEPROM_STEER_Y_GYRO_OFFSET_ADDR		38
#define EEPROM_STEER_Z_GYRO_OFFSET_ADDR		40
#define EEPROM_STEER_X_GYRO_OFFSET_MIN_ADDR	42
#define EEPROM_STEER_X_GYRO_OFFSET_MAX_ADDR	44
#define EEPROM_STEER_Y_GYRO_OFFSET_MIN_ADDR	46
#define EEPROM_STEER_Y_GYRO_OFFSET_MAX_ADDR	48
#define EEPROM_STEER_Z_GYRO_OFFSET_MIN_ADDR	50
#define EEPROM_STEER_Z_GYRO_OFFSET_MAX_ADDR	52

#define EEPROM_P_ADDR						54
#define EEPROM_D_ADDR						56
#define EEPROM_PD_SAVED_ADDR				58
#define EEPROM_P_OFF_ADDR					60
#define EEPROM_D_OFF_ADDR					62
#define EEPROM_PD_OFF_SAVED_ADDR			64

#define EEPROM_VOLTAGE_REF_ADDR				66
#define EEPROM_VOLTAGE_REF_SAVED_ADDR		68


#define PD_SAVED							1
